# Generated by Django 5.1.7 on 2025-03-16 21:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("solutions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="content",
            field=models.TextField(default="No content available"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="section",
            name="number",
            field=models.IntegerField(),
        ),
    ]
