# Generated by Django 5.1.7 on 2025-03-16 22:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("solutions", "0002_section_content_alter_section_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="problem",
            name="problem_number",
        ),
        migrations.AddField(
            model_name="problem",
            name="number",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="problem",
            name="description",
            field=models.TextField(),
        ),
    ]
