# Generated by Django 5.1.7 on 2025-03-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("solutions", "0005_update"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="section",
            name="content",
        ),
        migrations.AlterField(
            model_name="section",
            name="number",
            field=models.CharField(max_length=10),
        ),
    ]
