# Generated by Django 5.1.7 on 2025-03-20 23:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("solutions", "0006_remove_section_content_alter_section_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="problem",
            name="number",
        ),
        migrations.AddField(
            model_name="problem",
            name="problem_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="problem",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
