# Generated by Django 5.1.7 on 2025-03-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("solutions", "0007_remove_problem_number_problem_problem_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("published_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
