# Generated by Django 5.1.7 on 2025-03-26 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("solutions", "0008_about"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="support_resources/")),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
